on:
  push

name: Test LDC x64

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup LDC
        uses: mihails-strasuns/setup-dlang@v0.3.0
        with:
          compiler: ldc-latest
      - name: Build
        run: dub build -b release
      - name: Test
        run: dub test